### PR TITLE
Instructions on setting up from GitHub

### PR DESCRIPTION
**Pull request by AurynBeorn**

### CODE REVIEW

**Comment by AurynBeorn** [comment]
This addresses part of #5.

**Comment by Sei-Lisa** [comment]
It looks good to me, though I'd like @codeviolet to weigh in on it, specifically about the placement. It needs to be in a prominent place, but maybe that's too prominent and distracting for those who acquired it from Marketplace?

**Comment by codeviolet** [comment]
Thanks for doing this @AurynBeorn! Although I agree with @sei-lisa that it needs to be in a prominent place I think that the guide for importing the LSL scripts from GitHub is not really a part of the actual user instructions. 

With your permission I will use your text as the basis for a new PR to insert it elsewhere. What I would plan to do is insert it into the  [code repository](https://github.com/AVsitter/AVsitter) (either the README.md or a new file there) and link to that location in an alert box at the top of the AVsitter2_home.html page. Would that be ok?

**Comment by AurynBeorn** [comment]
No problem at all! Place the text where you think it's best.

**Comment by codeviolet** [comment]
Closing as this PR has been implemented by https://github.com/AVsitter/AVsitter/pull/30

**Pull request closed without merging**
