### PR TITLE
Updated documentation for MLP-converter script

### PR DESCRIPTION
**Pull request by AurynBeorn**
Completes #17

### CODE REVIEW

**Comment by Sei-Lisa** [comment]
I have some comments.

- There's no introduction to what it is for. Users that don't know what MLP is may not know whether they need this script for something.
- At this moment, it uses a very different approach to the rest of the page, maybe except for [AV]select; in any case the style change is very noticeable. I'm wondering if this text could be placed in a separate file linked from here. The idea is that those users who just need a reminder of how it works, can read a short description of the features (including in particular the offset in the description), but those needing a step-by-step guide on how to convert their creations have access to the full explanation. Being a technical person I always prefer short reference pages that go to the point, unless it's the first time and I need to learn the basics of how to use it. For example, if I need to find an answer to "where did I have to put the offset? was it in a notecard?" and then I go to the page, I expect to see only a concise explanation.
- This part may be subject to change soon (when I finish my work on the dump script, which is still in progress):
  >  - Drop the necessary AVsitter scripts into your object as well as this AVpos notecard.
  >  - Don't forget adding the [AV]adjuster script and the [AV]helper object.

  To make it more future-proof, I would word it along the lines of this:
  - Follow the instructions for a normal set-up, using the new AVpos notecard.
- This part:
  > - You may now delete the notecards beginning by .MENUITEMS and .POSITIONS.

  I would word it more like: "When you are satisfied with the result, you may delete..."

**Comment by Sei-Lisa** [comment]
It would be nice if @ScoutSchwager weighed in on this, by the way.

**Comment by Sei-Lisa** [comment]
Please proceed to make the suggested changes.

**Comment by AurynBeorn** [comment]
I've edited the first commit, doing as suggested.

**Comment by AurynBeorn** [comment]
Sorry about that!

**Comment by Sei-Lisa** [comment]
Looks good now. Thank you very much!

**Pull request merged**
