### PR TITLE
Whitespace cleanups

### PR DESCRIPTION
**Pull request by Sei-Lisa**
Fixes:

- Some files still had CRLF line terminators. Normalize them.
- Many files did not end in LF. Ensure they do.
- Files with tabs (most notably scripts) were being shown improperly on the web. Change tabs to spaces.
- Some lines had trailing spaces. Remove those.
- There were a few function calls which were displayed with a leading space. Remove it.

### CODE REVIEW

**Comment by AurynBeorn** [comment]
Looks good to me, and I really hope you've used some script to feed it all the files and do the job automatically :-)

There are a few changes, though, that I don't understand because they seem exactly the same to me. For example, in  _avsitter1_lsl_examples_advanced/avsitter1_lsl_example_animation_sequence.md I see this:

Line 97
<pre>- ```
+ ```</pre>

Same in:

-  _avsitter1_lsl_examples_beginner/avsitter1_lsl_example_give_item_with_button.md , line 23
-  _avsitter1_lsl_examples_beginner/avsitter1_lsl_example_give_item_with_pose.md , line 24
-  _avsitter2_lsl_examples_advanced/avsitter2_lsl_example_autoplay.md , lines 6 and 46
-  _avsitter2_lsl_examples_advanced/avsitter2_lsl_example_looped_sound_by_button.md , line 47
-  _avsitter2_lsl_examples_advanced/avsitter2_lsl_example_move_prim.md , line 102

etc.

I can look for _all_ the instances if you want. Why is there a change in those lines?

**Comment by Sei-Lisa** [comment]
I believe that's a bug in the GitHub display of the diff, where the 'No Newline at End of File' symbol is missing. If you look at the diff in text form, by appending `.patch` to the URL, you can see that these files lack an EOL in the last line in the original, and the commit adds one:

https://github.com/AVsitter/avsitter.github.io/commit/c10a2d92c6fdaf2711a6615ece75aa54255af3a5.patch

**Comment by AurynBeorn** [comment]
Ahhh... I see it now!

All good, then :-)

**Comment by Sei-Lisa** [comment]
I've submitted the problem to GitHub in case they are interested in fixing it.

Thanks for the review!

**Pull request merged**
