### PR TITLE
add team info

### PR DESCRIPTION
**Pull request by codeviolet**
Before merging, I would appreciate any feedback about the treatment I've given the team section. e.g. If there's an obvious way to do it better, etc. Hopefully it is all ok :) If we find people asking direct questions too much before researching the documentation then perhaps in future the team info could be moved to a different page other than /support.

### CODE REVIEW

**Comment by Sei-Lisa** [comment]
I like it; I think it's exactly what was needed. Thank you very much!

I'd suggest two changes.

1. I don't see group moderators as a position granting belonging to the team. They are necessary to keep peace, but it's very marginal to the team's activity and their intervention is very uncommon, as incivility is rare. Instead I'd suggest something like "Help and Support" as a position.
2. I suggest a reformatting of the list, to easily allow for listing more than one member in each category, as follows:

---

* Inworld Help and Support:
  * *(wanted)*
* Second Life Release Tester:
  * *(wanted)*
* OpenSim Release Tester:
  * *(wanted)*
* Code Developers:
  * [Sei Lisa](http://world.secondlife.com/resident/3c5aaad5-8c66-46a3-b574-cad02acf520d) (Lead Developer / Project Maintainer)
  * *(wanted)*
* Documentation Maintainer:
  * [Auryn Beorn](http://world.secondlife.com/resident/766f3817-2f2a-469d-acfa-9789080ecc85)
* Project Management / Project Creator:
  * [Code Violet](http://world.secondlife.com/resident/b30c9262-9abf-4cd1-9476-adcf5723c029)
* Marketplace Enquiries:
  * [AVsitter Resident](http://world.secondlife.com/resident/8c24c939-bbe9-4bd0-8868-b5b92cc90bc9)

---

Not sure if using headers (`#...` at the appropriate level) would work instead of bullet points.

**Comment by Sei-Lisa** [comment]
I left a double quote by mistake when converting the Auryn Beorn link to Markdown.

I've edited the list above but here it is again, in case you're copy/pasting from email:

* Inworld Help and Support:
  * *(wanted)*
* Second Life Release Tester:
  * *(wanted)*
* OpenSim Release Tester:
  * *(wanted)*
* Code Developers:
  * [Sei Lisa](http://world.secondlife.com/resident/3c5aaad5-8c66-46a3-b574-cad02acf520d) (Lead Developer / Project Maintainer)
  * *(wanted)*
* Documentation Maintainer:
  * [Auryn Beorn](http://world.secondlife.com/resident/766f3817-2f2a-469d-acfa-9789080ecc85)
* Project Management / Project Creator:
  * [Code Violet](http://world.secondlife.com/resident/b30c9262-9abf-4cd1-9476-adcf5723c029)
* Marketplace Enquiries:
  * [AVsitter Resident](http://world.secondlife.com/resident/8c24c939-bbe9-4bd0-8868-b5b92cc90bc9)

**Comment by AurynBeorn** [comment]
I like the classification, but I would suggest to use the `###` header for the categories and then `-` for the list of avatar names.

**Comment by codeviolet** [comment]
I've implemented the suggestions, thanks. "Group Moderator" was specifically chosen to be passive so as to not "throw that person under the bus" as it were, by implying that they should be contacted outside of the group. I've changed that title to "Inworld Group Support" - we can tweak as needed.

**Comment by Sei-Lisa** [comment]
Thank you very much. Merging. I'll send a group notice.

**Pull request merged**
